# Generated by Django 4.1.3 on 2022-11-06 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('date_borrowed', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('expected_return_date', models.DateTimeField(blank=True, null=True)),
                ('dat_returned', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bookcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='religion',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=90, null=True)),
                ('year_of_exp', models.CharField(blank=True, max_length=90, null=True)),
                ('advisory', models.CharField(max_length=90, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=90, null=True)),
                ('year', models.CharField(blank=True, max_length=90, null=True)),
                ('section', models.CharField(blank=True, max_length=90, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('action', models.CharField(blank=True, max_length=90, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bookcategory')),
                ('borrowedbook', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.borrowedbook')),
            ],
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=90, null=True)),
                ('title', models.CharField(blank=True, max_length=90, null=True)),
                ('authors', models.CharField(blank=True, max_length=300, null=True)),
                ('preface', models.TextField(blank=True, null=True)),
                ('old_quan', models.IntegerField(blank=True, null=True)),
                ('new_quan', models.IntegerField(blank=True, null=True)),
                ('available_quan', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.bookcategory')),
            ],
        ),
    ]
