# Generated by Django 4.1.3 on 2022-11-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookcategory_borrowedbook_remove_myuser_religion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
